# a mybinder.org-ready environment for demoing jupyterlab_wall
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab_wall-demo
#
name: jupyterlab_wall-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=4.0.0,<5.0.0a0
  # labextension build dependencies
  - nodejs >=18.0.0,<21
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
