name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install node
      uses: actions/setup-node@v4
      with:
       node-version: '18.x'
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install python dependencies
      run: |
        python -m pip install -U jupyterlab
        python -m pip install pytest pytest-cov pytest-jupyter
    - name: Build the extension
      run: |
        jlpm
        jlpm run eslint:check
        python -m pip install .
    - name: Run python tests
      run: |
        python -m pytest --cov=jupyterlab_wall jupyterlab_wall/tests
    - name: Run JS unit tests
      run: |
        jlpm test
    - name: Install node test dependencies
      run: |
        cd ui-tests
        jlpm install
        jlpm playwright install chromium
    - name: Run UI tests
      run: |
        cd ui-tests
        jlpm test
    - name: Check the extension
      if: ( startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS') )
      run: |
        jupyter server extension list 2>&1 | tee serverextension.list
        cat serverextension.list | grep -ie "jupyterlab_wall.*OK"
        jupyter labextension list 2>&1 | tee labextension.list
        cat labextension.list | grep -ie "jupyterlab-wall.*OK"
    - name: Run the browser_check
      run: python -m jupyterlab.browser_check
